// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MQAA.proto

#ifndef PROTOBUF_MQAA_2eproto__INCLUDED
#define PROTOBUF_MQAA_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ec {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MQAA_2eproto();
void protobuf_AssignDesc_MQAA_2eproto();
void protobuf_ShutdownFile_MQAA_2eproto();

class LoginRequest;
class LoginResponse;
class ZhuTiCanShu;
class ZhuTiCanShuResponse;

// ===================================================================

class LoginRequest : public ::google::protobuf::Message {
 public:
  LoginRequest();
  virtual ~LoginRequest();

  LoginRequest(const LoginRequest& from);

  inline LoginRequest& operator=(const LoginRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRequest& default_instance();

  void Swap(LoginRequest* other);

  // implements Message ----------------------------------------------

  inline LoginRequest* New() const { return New(NULL); }

  LoginRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRequest& from);
  void MergeFrom(const LoginRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LoginRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes username = 1;
  bool has_username() const;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  void set_username(const char* value);
  void set_username(const void* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // optional string password = 2;
  bool has_password() const;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:ec.LoginRequest)
 private:
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_password();
  inline void clear_has_password();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  friend void  protobuf_AddDesc_MQAA_2eproto();
  friend void protobuf_AssignDesc_MQAA_2eproto();
  friend void protobuf_ShutdownFile_MQAA_2eproto();

  void InitAsDefaultInstance();
  static LoginRequest* default_instance_;
};
// -------------------------------------------------------------------

class LoginResponse : public ::google::protobuf::Message {
 public:
  LoginResponse();
  virtual ~LoginResponse();

  LoginResponse(const LoginResponse& from);

  inline LoginResponse& operator=(const LoginResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginResponse& default_instance();

  void Swap(LoginResponse* other);

  // implements Message ----------------------------------------------

  inline LoginResponse* New() const { return New(NULL); }

  LoginResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginResponse& from);
  void MergeFrom(const LoginResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LoginResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required fixed32 ttl = 1;
  bool has_ttl() const;
  void clear_ttl();
  static const int kTtlFieldNumber = 1;
  ::google::protobuf::uint32 ttl() const;
  void set_ttl(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ec.LoginResponse)
 private:
  inline void set_has_ttl();
  inline void clear_has_ttl();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 ttl_;
  friend void  protobuf_AddDesc_MQAA_2eproto();
  friend void protobuf_AssignDesc_MQAA_2eproto();
  friend void protobuf_ShutdownFile_MQAA_2eproto();

  void InitAsDefaultInstance();
  static LoginResponse* default_instance_;
};
// -------------------------------------------------------------------

class ZhuTiCanShu : public ::google::protobuf::Message {
 public:
  ZhuTiCanShu();
  virtual ~ZhuTiCanShu();

  ZhuTiCanShu(const ZhuTiCanShu& from);

  inline ZhuTiCanShu& operator=(const ZhuTiCanShu& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZhuTiCanShu& default_instance();

  void Swap(ZhuTiCanShu* other);

  // implements Message ----------------------------------------------

  inline ZhuTiCanShu* New() const { return New(NULL); }

  ZhuTiCanShu* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ZhuTiCanShu& from);
  void MergeFrom(const ZhuTiCanShu& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ZhuTiCanShu* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string opt = 1;
  bool has_opt() const;
  void clear_opt();
  static const int kOptFieldNumber = 1;
  const ::std::string& opt() const;
  void set_opt(const ::std::string& value);
  void set_opt(const char* value);
  void set_opt(const char* value, size_t size);
  ::std::string* mutable_opt();
  ::std::string* release_opt();
  void set_allocated_opt(::std::string* opt);

  // required float doukou = 2;
  bool has_doukou() const;
  void clear_doukou();
  static const int kDoukouFieldNumber = 2;
  float doukou() const;
  void set_doukou(float value);

  // optional string jiegouxingshi = 3;
  bool has_jiegouxingshi() const;
  void clear_jiegouxingshi();
  static const int kJiegouxingshiFieldNumber = 3;
  const ::std::string& jiegouxingshi() const;
  void set_jiegouxingshi(const ::std::string& value);
  void set_jiegouxingshi(const char* value);
  void set_jiegouxingshi(const char* value, size_t size);
  ::std::string* mutable_jiegouxingshi();
  ::std::string* release_jiegouxingshi();
  void set_allocated_jiegouxingshi(::std::string* jiegouxingshi);

  // optional fixed32 tanshu = 4;
  bool has_tanshu() const;
  void clear_tanshu();
  static const int kTanshuFieldNumber = 4;
  ::google::protobuf::uint32 tanshu() const;
  void set_tanshu(::google::protobuf::uint32 value);

  // optional string langxingshi = 5;
  bool has_langxingshi() const;
  void clear_langxingshi();
  static const int kLangxingshiFieldNumber = 5;
  const ::std::string& langxingshi() const;
  void set_langxingshi(const ::std::string& value);
  void set_langxingshi(const char* value);
  void set_langxingshi(const char* value, size_t size);
  ::std::string* mutable_langxingshi();
  ::std::string* release_langxingshi();
  void set_allocated_langxingshi(::std::string* langxingshi);

  // optional fixed32 jianshu = 6;
  bool has_jianshu() const;
  void clear_jianshu();
  static const int kJianshuFieldNumber = 6;
  ::google::protobuf::uint32 jianshu() const;
  void set_jianshu(::google::protobuf::uint32 value);

  // required float zuo3miankuo = 7;
  bool has_zuo3miankuo() const;
  void clear_zuo3miankuo();
  static const int kZuo3MiankuoFieldNumber = 7;
  float zuo3miankuo() const;
  void set_zuo3miankuo(float value);

  // required float zuo2miankuo = 8;
  bool has_zuo2miankuo() const;
  void clear_zuo2miankuo();
  static const int kZuo2MiankuoFieldNumber = 8;
  float zuo2miankuo() const;
  void set_zuo2miankuo(float value);

  // required float zuo1miankuo = 9;
  bool has_zuo1miankuo() const;
  void clear_zuo1miankuo();
  static const int kZuo1MiankuoFieldNumber = 9;
  float zuo1miankuo() const;
  void set_zuo1miankuo(float value);

  // required float mingjianmiankuo = 10;
  bool has_mingjianmiankuo() const;
  void clear_mingjianmiankuo();
  static const int kMingjianmiankuoFieldNumber = 10;
  float mingjianmiankuo() const;
  void set_mingjianmiankuo(float value);

  // required float you1miankuo = 11;
  bool has_you1miankuo() const;
  void clear_you1miankuo();
  static const int kYou1MiankuoFieldNumber = 11;
  float you1miankuo() const;
  void set_you1miankuo(float value);

  // @@protoc_insertion_point(class_scope:ec.ZhuTiCanShu)
 private:
  inline void set_has_opt();
  inline void clear_has_opt();
  inline void set_has_doukou();
  inline void clear_has_doukou();
  inline void set_has_jiegouxingshi();
  inline void clear_has_jiegouxingshi();
  inline void set_has_tanshu();
  inline void clear_has_tanshu();
  inline void set_has_langxingshi();
  inline void clear_has_langxingshi();
  inline void set_has_jianshu();
  inline void clear_has_jianshu();
  inline void set_has_zuo3miankuo();
  inline void clear_has_zuo3miankuo();
  inline void set_has_zuo2miankuo();
  inline void clear_has_zuo2miankuo();
  inline void set_has_zuo1miankuo();
  inline void clear_has_zuo1miankuo();
  inline void set_has_mingjianmiankuo();
  inline void clear_has_mingjianmiankuo();
  inline void set_has_you1miankuo();
  inline void clear_has_you1miankuo();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr opt_;
  ::google::protobuf::internal::ArenaStringPtr jiegouxingshi_;
  float doukou_;
  ::google::protobuf::uint32 tanshu_;
  ::google::protobuf::internal::ArenaStringPtr langxingshi_;
  ::google::protobuf::uint32 jianshu_;
  float zuo3miankuo_;
  float zuo2miankuo_;
  float zuo1miankuo_;
  float mingjianmiankuo_;
  float you1miankuo_;
  friend void  protobuf_AddDesc_MQAA_2eproto();
  friend void protobuf_AssignDesc_MQAA_2eproto();
  friend void protobuf_ShutdownFile_MQAA_2eproto();

  void InitAsDefaultInstance();
  static ZhuTiCanShu* default_instance_;
};
// -------------------------------------------------------------------

class ZhuTiCanShuResponse : public ::google::protobuf::Message {
 public:
  ZhuTiCanShuResponse();
  virtual ~ZhuTiCanShuResponse();

  ZhuTiCanShuResponse(const ZhuTiCanShuResponse& from);

  inline ZhuTiCanShuResponse& operator=(const ZhuTiCanShuResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZhuTiCanShuResponse& default_instance();

  void Swap(ZhuTiCanShuResponse* other);

  // implements Message ----------------------------------------------

  inline ZhuTiCanShuResponse* New() const { return New(NULL); }

  ZhuTiCanShuResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ZhuTiCanShuResponse& from);
  void MergeFrom(const ZhuTiCanShuResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ZhuTiCanShuResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string ok = 1;
  bool has_ok() const;
  void clear_ok();
  static const int kOkFieldNumber = 1;
  const ::std::string& ok() const;
  void set_ok(const ::std::string& value);
  void set_ok(const char* value);
  void set_ok(const char* value, size_t size);
  ::std::string* mutable_ok();
  ::std::string* release_ok();
  void set_allocated_ok(::std::string* ok);

  // @@protoc_insertion_point(class_scope:ec.ZhuTiCanShuResponse)
 private:
  inline void set_has_ok();
  inline void clear_has_ok();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr ok_;
  friend void  protobuf_AddDesc_MQAA_2eproto();
  friend void protobuf_AssignDesc_MQAA_2eproto();
  friend void protobuf_ShutdownFile_MQAA_2eproto();

  void InitAsDefaultInstance();
  static ZhuTiCanShuResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginRequest

// required bytes username = 1;
inline bool LoginRequest::has_username() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginRequest::set_has_username() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginRequest::clear_has_username() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginRequest::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_username();
}
inline const ::std::string& LoginRequest::username() const {
  // @@protoc_insertion_point(field_get:ec.LoginRequest.username)
  return username_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_username(const ::std::string& value) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ec.LoginRequest.username)
}
inline void LoginRequest::set_username(const char* value) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ec.LoginRequest.username)
}
inline void LoginRequest::set_username(const void* value, size_t size) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ec.LoginRequest.username)
}
inline ::std::string* LoginRequest::mutable_username() {
  set_has_username();
  // @@protoc_insertion_point(field_mutable:ec.LoginRequest.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRequest::release_username() {
  clear_has_username();
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    set_has_username();
  } else {
    clear_has_username();
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:ec.LoginRequest.username)
}

// optional string password = 2;
inline bool LoginRequest::has_password() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginRequest::set_has_password() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginRequest::clear_has_password() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginRequest::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_password();
}
inline const ::std::string& LoginRequest::password() const {
  // @@protoc_insertion_point(field_get:ec.LoginRequest.password)
  return password_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_password(const ::std::string& value) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ec.LoginRequest.password)
}
inline void LoginRequest::set_password(const char* value) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ec.LoginRequest.password)
}
inline void LoginRequest::set_password(const char* value, size_t size) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ec.LoginRequest.password)
}
inline ::std::string* LoginRequest::mutable_password() {
  set_has_password();
  // @@protoc_insertion_point(field_mutable:ec.LoginRequest.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoginRequest::release_password() {
  clear_has_password();
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoginRequest::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    set_has_password();
  } else {
    clear_has_password();
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:ec.LoginRequest.password)
}

// -------------------------------------------------------------------

// LoginResponse

// required fixed32 ttl = 1;
inline bool LoginResponse::has_ttl() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginResponse::set_has_ttl() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginResponse::clear_has_ttl() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginResponse::clear_ttl() {
  ttl_ = 0u;
  clear_has_ttl();
}
inline ::google::protobuf::uint32 LoginResponse::ttl() const {
  // @@protoc_insertion_point(field_get:ec.LoginResponse.ttl)
  return ttl_;
}
inline void LoginResponse::set_ttl(::google::protobuf::uint32 value) {
  set_has_ttl();
  ttl_ = value;
  // @@protoc_insertion_point(field_set:ec.LoginResponse.ttl)
}

// -------------------------------------------------------------------

// ZhuTiCanShu

// required string opt = 1;
inline bool ZhuTiCanShu::has_opt() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ZhuTiCanShu::set_has_opt() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ZhuTiCanShu::clear_has_opt() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ZhuTiCanShu::clear_opt() {
  opt_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_opt();
}
inline const ::std::string& ZhuTiCanShu::opt() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.opt)
  return opt_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZhuTiCanShu::set_opt(const ::std::string& value) {
  set_has_opt();
  opt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.opt)
}
inline void ZhuTiCanShu::set_opt(const char* value) {
  set_has_opt();
  opt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ec.ZhuTiCanShu.opt)
}
inline void ZhuTiCanShu::set_opt(const char* value, size_t size) {
  set_has_opt();
  opt_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ec.ZhuTiCanShu.opt)
}
inline ::std::string* ZhuTiCanShu::mutable_opt() {
  set_has_opt();
  // @@protoc_insertion_point(field_mutable:ec.ZhuTiCanShu.opt)
  return opt_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZhuTiCanShu::release_opt() {
  clear_has_opt();
  return opt_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZhuTiCanShu::set_allocated_opt(::std::string* opt) {
  if (opt != NULL) {
    set_has_opt();
  } else {
    clear_has_opt();
  }
  opt_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), opt);
  // @@protoc_insertion_point(field_set_allocated:ec.ZhuTiCanShu.opt)
}

// required float doukou = 2;
inline bool ZhuTiCanShu::has_doukou() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ZhuTiCanShu::set_has_doukou() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ZhuTiCanShu::clear_has_doukou() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ZhuTiCanShu::clear_doukou() {
  doukou_ = 0;
  clear_has_doukou();
}
inline float ZhuTiCanShu::doukou() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.doukou)
  return doukou_;
}
inline void ZhuTiCanShu::set_doukou(float value) {
  set_has_doukou();
  doukou_ = value;
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.doukou)
}

// optional string jiegouxingshi = 3;
inline bool ZhuTiCanShu::has_jiegouxingshi() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ZhuTiCanShu::set_has_jiegouxingshi() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ZhuTiCanShu::clear_has_jiegouxingshi() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ZhuTiCanShu::clear_jiegouxingshi() {
  jiegouxingshi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_jiegouxingshi();
}
inline const ::std::string& ZhuTiCanShu::jiegouxingshi() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.jiegouxingshi)
  return jiegouxingshi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZhuTiCanShu::set_jiegouxingshi(const ::std::string& value) {
  set_has_jiegouxingshi();
  jiegouxingshi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.jiegouxingshi)
}
inline void ZhuTiCanShu::set_jiegouxingshi(const char* value) {
  set_has_jiegouxingshi();
  jiegouxingshi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ec.ZhuTiCanShu.jiegouxingshi)
}
inline void ZhuTiCanShu::set_jiegouxingshi(const char* value, size_t size) {
  set_has_jiegouxingshi();
  jiegouxingshi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ec.ZhuTiCanShu.jiegouxingshi)
}
inline ::std::string* ZhuTiCanShu::mutable_jiegouxingshi() {
  set_has_jiegouxingshi();
  // @@protoc_insertion_point(field_mutable:ec.ZhuTiCanShu.jiegouxingshi)
  return jiegouxingshi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZhuTiCanShu::release_jiegouxingshi() {
  clear_has_jiegouxingshi();
  return jiegouxingshi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZhuTiCanShu::set_allocated_jiegouxingshi(::std::string* jiegouxingshi) {
  if (jiegouxingshi != NULL) {
    set_has_jiegouxingshi();
  } else {
    clear_has_jiegouxingshi();
  }
  jiegouxingshi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), jiegouxingshi);
  // @@protoc_insertion_point(field_set_allocated:ec.ZhuTiCanShu.jiegouxingshi)
}

// optional fixed32 tanshu = 4;
inline bool ZhuTiCanShu::has_tanshu() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ZhuTiCanShu::set_has_tanshu() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ZhuTiCanShu::clear_has_tanshu() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ZhuTiCanShu::clear_tanshu() {
  tanshu_ = 0u;
  clear_has_tanshu();
}
inline ::google::protobuf::uint32 ZhuTiCanShu::tanshu() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.tanshu)
  return tanshu_;
}
inline void ZhuTiCanShu::set_tanshu(::google::protobuf::uint32 value) {
  set_has_tanshu();
  tanshu_ = value;
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.tanshu)
}

// optional string langxingshi = 5;
inline bool ZhuTiCanShu::has_langxingshi() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ZhuTiCanShu::set_has_langxingshi() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ZhuTiCanShu::clear_has_langxingshi() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ZhuTiCanShu::clear_langxingshi() {
  langxingshi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_langxingshi();
}
inline const ::std::string& ZhuTiCanShu::langxingshi() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.langxingshi)
  return langxingshi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZhuTiCanShu::set_langxingshi(const ::std::string& value) {
  set_has_langxingshi();
  langxingshi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.langxingshi)
}
inline void ZhuTiCanShu::set_langxingshi(const char* value) {
  set_has_langxingshi();
  langxingshi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ec.ZhuTiCanShu.langxingshi)
}
inline void ZhuTiCanShu::set_langxingshi(const char* value, size_t size) {
  set_has_langxingshi();
  langxingshi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ec.ZhuTiCanShu.langxingshi)
}
inline ::std::string* ZhuTiCanShu::mutable_langxingshi() {
  set_has_langxingshi();
  // @@protoc_insertion_point(field_mutable:ec.ZhuTiCanShu.langxingshi)
  return langxingshi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZhuTiCanShu::release_langxingshi() {
  clear_has_langxingshi();
  return langxingshi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZhuTiCanShu::set_allocated_langxingshi(::std::string* langxingshi) {
  if (langxingshi != NULL) {
    set_has_langxingshi();
  } else {
    clear_has_langxingshi();
  }
  langxingshi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), langxingshi);
  // @@protoc_insertion_point(field_set_allocated:ec.ZhuTiCanShu.langxingshi)
}

// optional fixed32 jianshu = 6;
inline bool ZhuTiCanShu::has_jianshu() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ZhuTiCanShu::set_has_jianshu() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ZhuTiCanShu::clear_has_jianshu() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ZhuTiCanShu::clear_jianshu() {
  jianshu_ = 0u;
  clear_has_jianshu();
}
inline ::google::protobuf::uint32 ZhuTiCanShu::jianshu() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.jianshu)
  return jianshu_;
}
inline void ZhuTiCanShu::set_jianshu(::google::protobuf::uint32 value) {
  set_has_jianshu();
  jianshu_ = value;
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.jianshu)
}

// required float zuo3miankuo = 7;
inline bool ZhuTiCanShu::has_zuo3miankuo() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ZhuTiCanShu::set_has_zuo3miankuo() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ZhuTiCanShu::clear_has_zuo3miankuo() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ZhuTiCanShu::clear_zuo3miankuo() {
  zuo3miankuo_ = 0;
  clear_has_zuo3miankuo();
}
inline float ZhuTiCanShu::zuo3miankuo() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.zuo3miankuo)
  return zuo3miankuo_;
}
inline void ZhuTiCanShu::set_zuo3miankuo(float value) {
  set_has_zuo3miankuo();
  zuo3miankuo_ = value;
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.zuo3miankuo)
}

// required float zuo2miankuo = 8;
inline bool ZhuTiCanShu::has_zuo2miankuo() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ZhuTiCanShu::set_has_zuo2miankuo() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ZhuTiCanShu::clear_has_zuo2miankuo() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ZhuTiCanShu::clear_zuo2miankuo() {
  zuo2miankuo_ = 0;
  clear_has_zuo2miankuo();
}
inline float ZhuTiCanShu::zuo2miankuo() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.zuo2miankuo)
  return zuo2miankuo_;
}
inline void ZhuTiCanShu::set_zuo2miankuo(float value) {
  set_has_zuo2miankuo();
  zuo2miankuo_ = value;
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.zuo2miankuo)
}

// required float zuo1miankuo = 9;
inline bool ZhuTiCanShu::has_zuo1miankuo() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ZhuTiCanShu::set_has_zuo1miankuo() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ZhuTiCanShu::clear_has_zuo1miankuo() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ZhuTiCanShu::clear_zuo1miankuo() {
  zuo1miankuo_ = 0;
  clear_has_zuo1miankuo();
}
inline float ZhuTiCanShu::zuo1miankuo() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.zuo1miankuo)
  return zuo1miankuo_;
}
inline void ZhuTiCanShu::set_zuo1miankuo(float value) {
  set_has_zuo1miankuo();
  zuo1miankuo_ = value;
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.zuo1miankuo)
}

// required float mingjianmiankuo = 10;
inline bool ZhuTiCanShu::has_mingjianmiankuo() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void ZhuTiCanShu::set_has_mingjianmiankuo() {
  _has_bits_[0] |= 0x00000200u;
}
inline void ZhuTiCanShu::clear_has_mingjianmiankuo() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void ZhuTiCanShu::clear_mingjianmiankuo() {
  mingjianmiankuo_ = 0;
  clear_has_mingjianmiankuo();
}
inline float ZhuTiCanShu::mingjianmiankuo() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.mingjianmiankuo)
  return mingjianmiankuo_;
}
inline void ZhuTiCanShu::set_mingjianmiankuo(float value) {
  set_has_mingjianmiankuo();
  mingjianmiankuo_ = value;
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.mingjianmiankuo)
}

// required float you1miankuo = 11;
inline bool ZhuTiCanShu::has_you1miankuo() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void ZhuTiCanShu::set_has_you1miankuo() {
  _has_bits_[0] |= 0x00000400u;
}
inline void ZhuTiCanShu::clear_has_you1miankuo() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void ZhuTiCanShu::clear_you1miankuo() {
  you1miankuo_ = 0;
  clear_has_you1miankuo();
}
inline float ZhuTiCanShu::you1miankuo() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShu.you1miankuo)
  return you1miankuo_;
}
inline void ZhuTiCanShu::set_you1miankuo(float value) {
  set_has_you1miankuo();
  you1miankuo_ = value;
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShu.you1miankuo)
}

// -------------------------------------------------------------------

// ZhuTiCanShuResponse

// required string ok = 1;
inline bool ZhuTiCanShuResponse::has_ok() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ZhuTiCanShuResponse::set_has_ok() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ZhuTiCanShuResponse::clear_has_ok() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ZhuTiCanShuResponse::clear_ok() {
  ok_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_ok();
}
inline const ::std::string& ZhuTiCanShuResponse::ok() const {
  // @@protoc_insertion_point(field_get:ec.ZhuTiCanShuResponse.ok)
  return ok_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZhuTiCanShuResponse::set_ok(const ::std::string& value) {
  set_has_ok();
  ok_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ec.ZhuTiCanShuResponse.ok)
}
inline void ZhuTiCanShuResponse::set_ok(const char* value) {
  set_has_ok();
  ok_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ec.ZhuTiCanShuResponse.ok)
}
inline void ZhuTiCanShuResponse::set_ok(const char* value, size_t size) {
  set_has_ok();
  ok_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ec.ZhuTiCanShuResponse.ok)
}
inline ::std::string* ZhuTiCanShuResponse::mutable_ok() {
  set_has_ok();
  // @@protoc_insertion_point(field_mutable:ec.ZhuTiCanShuResponse.ok)
  return ok_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ZhuTiCanShuResponse::release_ok() {
  clear_has_ok();
  return ok_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ZhuTiCanShuResponse::set_allocated_ok(::std::string* ok) {
  if (ok != NULL) {
    set_has_ok();
  } else {
    clear_has_ok();
  }
  ok_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ok);
  // @@protoc_insertion_point(field_set_allocated:ec.ZhuTiCanShuResponse.ok)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ec

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MQAA_2eproto__INCLUDED
